import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/plugins.css";
import "../../public/assets/css/style.css";

import { CartProvider } from "../components/header/CartContext";
import { WishlistProvider } from "../components/header/WishlistContext";
import { CompareProvider } from "../components/header/CompareContext";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Providers from "@/providers/ReduxProvider";
import BottomNav from "@/components/footer/BottomNav";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  weight: ["400", "500", "600", "700"], // add weights you need
});

export const metadata: Metadata = {
  title: "Online Shopping for Womens, Men, Kids Fashion & Lifestyle - big Sell",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/assets/images/logo/logo.png",
        type: "image/x-icon",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} font-sans`}>
        <Providers>
          <CompareProvider>
            <WishlistProvider>
              <CartProvider>
                {children}
                <ToastContainer position="top-right" autoClose={3000} />
              </CartProvider>
            </WishlistProvider>
          </CompareProvider>
          <BottomNav />
        </Providers>
      </body>
    </html>
  );
}
